// Renamed to index.export.ts to avoid Nuxt auto-registration conflict
export { default as Table } from '../../table/Table.vue'
export { default as TableBody } from '../../table/TableBody.vue'
export { default as TableCaption } from '../../table/TableCaption.vue'
export { default as TableCell } from '../../table/TableCell.vue'
export { default as TableEmpty } from '../../table/TableEmpty.vue'
export { default as TableFooter } from '../../table/TableFooter.vue'
export { default as TableHead } from '../../table/TableHead.vue'
export { default as TableHeader } from '../../table/TableHeader.vue'
export { default as TableRow } from '../../table/TableRow.vue'
