// Renamed to index.export.ts to avoid Nuxt auto-registration conflict
export { default as Dialog } from '../../dialog/Dialog.vue'
export { default as DialogClose } from '../../dialog/DialogClose.vue'
export { default as DialogContent } from '../../dialog/DialogContent.vue'
export { default as DialogDescription } from '../../dialog/DialogDescription.vue'
export { default as DialogFooter } from '../../dialog/DialogFooter.vue'
export { default as DialogHeader } from '../../dialog/DialogHeader.vue'
export { default as DialogOverlay } from '../../dialog/DialogOverlay.vue'
export { default as DialogScrollContent } from '../../dialog/DialogScrollContent.vue'
export { default as DialogTitle } from '../../dialog/DialogTitle.vue'
export { default as DialogTrigger } from '../../dialog/DialogTrigger.vue'
